config/routes.rb
Rails.application.routes.draw do
  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'

  mount ActionCable.server, at: '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/chatroom.rb
class Chatroom < ApplicationRecord
  
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(15) }
end

app/models/session.rb
class Session < ApplicationRecord

end

app/models/user.rb
class User < ApplicationRecord
  has_many :messages
  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: { minimum: 3, maximum: 20 }
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:warning] = "You must be logged in to perform this action"
      redirect_to login_path
    end
  end

end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController
  before_action :require_user
  
  def index
    @message = Message.new
    @messages = Message.custom_display
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_user

  def create
    message = current_user.messages.build(message_params)
    if message.save
      ActionCable.server.broadcast "chatroom_channel", mod_message: message_render(message)
    end
  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

  def message_render(message)
    render(partial: 'message', locals: {message: message})
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :logged_in_redirect, only: [:new, :create]

  def new

  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "You have successfully logged in"
      redirect_to root_path
    else
      flash.now[:warning] = "Please re-enter your credentials"
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You have logged out"
    redirect_to login_path
  end

  private

  def logged_in_redirect
    if logged_in?
      flash[:warning] = "You are already logged in"
      redirect_to root_path
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new 

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatroom/index.html.erb
<div class="container mt-5 mb-5">
  
  <div class="row mb-5">
    
    <div class="col">
      <h1 class="display-6">Welcome to SimplyConnect</h1>
      <h1 class="lead text-muted">Get right to your chats, no fuss!</h1>
    </div>
  
  </div>
  
  <div class="row">
    
    <div class="col-3">
      <ul class="list-group shadow">
        <li class="list-group-item">
          <strong>Users</strong>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Sapana
          <% if logged_in? %>
            <span class="badge bg-success rounded-pill">Online</span>
          <% end %>
        </li>
        <li class="list-group-item d-flex justify-content-between align-items-center">
          Venkat
          <% if logged_in? %>
            <span class="badge bg-success rounded-pill">Online</span>
          <% end %>
        </li>
      </ul>
    </div>

    <div class="col-9">
      <div class="card shadow" style="height: 30rem;">
        <div class="card-header">
          Activity
        </div>
        <div class="card-body" id = "message-container">
          <%= render @messages %>
        </div>
        <div class="card-footer">
          <%= form_for(@message, html: {class: "form"}, url: message_path, remote: true) do |f| %>
            <div class="input-group mb-2 mt-2">
              <%= f.text_field :body, class: "form-control", id: "message-body", placeholder: "Enter your message" %>
              <%= f.button "Send", class: "btn btn-warning" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  
  </div>

</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container">
    
    <a><%= image_tag("SimplyConnect.png", id: "navbar-logo") %></a>
    <%= link_to "SimplyConnect", root_path, class: "navbar-brand" %>
    
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a><%= link_to "Chatroom", root_path, class: "nav-link" %></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="#">Messages</a>
        </li>
      </ul>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
          Account
        </a>
        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          <% if logged_in? %>
            <li><a class="dropdown-item" href="#">Edit account</a></li>
          <% else %>
            <li><%= link_to "Login", login_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </li>
      <li>
        <div class="btn-nav ms-2">
          <% if !logged_in? %>
            <li><%= link_to "Signup", login_path, class: "btn btn-warning btn-small navbar-btn" %></li>
          <% else %>
            <li><%= link_to "Logout", logout_path, method: :delete, class: "btn btn-warning btn-small navbar-btn" %></li>
          <% end %>
        </div>
      </li>
    </ul>
  
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SimplyConnect</title>
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <%= render 'shared/messages' %>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="text mb-1">
  <a class="fst-italic text-decoration-none"><%= message.user.username %>:</a>
  <%= message.body %>
</div>

app/views/pages/home.html.erb
<h1>Welcome to MessageMe</h1>

app/views/shared/_form.html.erb
<div class="page-centered">
  <div class="card shadow">
  <h2 class="text-center mt-4 mb-4">Login</h2>
    <%= form_for(:session, html: {class: "form"}, url: login_path) do |f| %>
      <div class="form-group p-3">
          <%= f.text_field :username, placeholder: "Username", class: "form-control form-input" %>
      </div>
      <div class="form-group p-3">
          <%= f.password_field :password, placeholder: "Password", class: "form-control form-input" %>
      </div>
      <%= f.button "Login", class: "form-submit" %>
      </br>
      <h6 class="login-h6 text-center mb-4">New user? Signup</h6>
    <% end %>
  </div>
</div>

app/views/shared/_messages.html.erb
<div class="container mt-4">
  <% flash.each do |message_type, message_content| %>
    <div class="alert alert-<%=message_type%> alert-dismissible fade show" role="alert">
      <%= message_content %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>